export const SET_ERROR = "@@LOGIN/LOGIN_SET_ERROR";
export const SET_LOADING = "@@LOGIN/LOGIN_SET_LOADING";
export const LOGIN_SUCCES = "@@LOGIN/LOGIN_LOGIN_SUCCES";
export const LOGOUT = "@@LOGIN/LOGIN_LOGOUT";
export const LOGIN_ERROR = "@@/LOGIN_LOGIN_ERROR";
